version: "3.3"
services:
  nodeserver:
    build:
      context: ./app
    image: pkpa/nodeserver
    ports:
      - "5000:5000"
    volumes:
      - ./app:/home/node/app
    depends_on:
      - db
      - cache
      - mongodb
    networks:
      - app-network
  # webserver:
  #   image: nginx:1.21-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d/:ro
  #     - ./data/certbot/etc/letsencrypt:/etc/letsencrypt
  #     - ./data/certbot/var/lib/letsencrypt:/var/lib/letsencrypt/:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  #   depends_on:
  #     - nodeserver
  # certbot:
  #   image: certbot/certbot:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www/:/var/www/certbot/:rw
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   depends_on:
  #     - webserver
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
#    restart: always
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data/db/data:/var/lib/postgresql/data
      - ./data/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app-network
  cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./data/cache:/data
    networks:
      - app-network
  mongodb:
    container_name: mongodb
    image: mongo:5.0.4-focal
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
      - ./config/mongo/mongod.conf:/etc/mongod.conf
    ports:
      - "27017:27017"
    # command: [--auth]
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    #   - MONGO_INITDB_DATABASE=pkpa
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
